version: '3'

services:
  redis:
    container_name: "code-interpreter-redis"
    image: redis:7.2.4
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  api:
    container_name: "code-interpreter-api"
    environment:
      DEBUG: "true"
      REDIS_MODE: "standalone"
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    command: >
      bash -c "gunicorn -t 600 -w 5 --bind 0.0.0.0:8000 --reload --threads 10 app:app"
    volumes:
      - ./:/app
      - ./cache:/tmp/cache
    ports:
      - "8100:8000"

volumes:
  redis_data:
